USE [master]
GO

/****** Object:  Database [Dance]    Script Date: 13.12.2023 19:58:13 ******/
CREATE DATABASE [Dance]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Dance.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Dance_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dance] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dance] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Dance] SET  MULTI_USER 
GO

ALTER DATABASE [Dance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dance] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dance] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dance] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Dance] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Dance] SET  READ_WRITE 
GO

